[build]
  command = "npm run build"
  publish = "build"
  # functions = "netlify/functions"  # Uncomment if you have Netlify Functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Netlify Dev settings
#[dev]
#  command = "npm start"  # Command to start your dev server
#  port = 3000          # Port that the dev server will be listening on
#  publish = "build"      # Folder with the static content
